version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.9 # Use the appropriate Python image
    steps:
      - checkout # Pull the latest code from the repository
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt # Install dependencies
      - run:
          name: Run tests
          command: pytest tests.py # Replace with your test file name

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
