version: 2.1 # CircleCI config version

# Define the jobs (individual tasks that CircleCI runs)
jobs:
  test:
    docker:
      - image: circleci/python:3.9 # Use a Docker image with Python
    steps:
      - checkout # Checkout the repository code
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt # Install dependencies from requirements.txt
      - run:
          name: Run tests
          command: pytest

# Define workflows (orchestrate the order of jobs)
workflows:
  version: 2
  test-workflow: # Name of the workflow
    jobs:
